### Create a new Info entry (without photo)
POST http://localhost:3000/batches
Content-Type: application/json

{ "date": "2025-09-19", "notes": "31 May fry doing well" }

###

### Get all Info entries
GET http://localhost:3000/batches

###